### ISSUE TITLE
Ubuntu 19-04

### ISSUE THREAD

**Issue by titio72** [Diveboard/DC-agent#15]
Hi - any plan to build it for the new ubuntu?

**Comment by the0ne** [comment]
Didn't test it out yet - what's the issue on 19.04?

**Comment by titio72** [comment]
Several dependencies missing (I'm trying to fix them by using older
packages).
Building from github fails too. Right now I'm stuck with something related
to wxwidgets - but I didn't spend much time on it.

Cheers,

**Comment by titio72** [comment]
Hi,

did you see this before?

/home/aboni/Downloads/DC-agent/source/FacebookAuthDialog.h:16:3: error:
‘wxWebView’ does not name a type; did you mean ‘wxWeakRef’?
   wxWebView* m_WebView;

Thanks,
A.

**Comment by the0ne** [comment]
I have updated https://github.com/the0ne/DC-agent/ with several fixes to build on 19.04.
The README there has been updated as well to reflect the updated package requirements.

The resulting [diveboard-agent-20181102-x86_64.deb.zip](https://github.com/Diveboard/DC-agent/files/3350006/diveboard-agent-20181102-x86_64.deb.zip) looks good so far.
Please let me know in case you experience problems.

**Comment by titio72** [comment]
Great! Thanks.

I'll let you know if I find issues.

Cheers,
A.

**Comment by the0ne** [comment]
Hi @titio72 any feedback yet?

**Comment by titio72** [comment]
Hi Thomas,

sorry I didn't get back to you sooner.
Yes - it works perfectly.

Thanks,
A.
